const express = require('express')
const { port } = require('./config/config')
const { version } = require('../package.json')
const router = require('./router')

const app = express()
app.use(express.json())
app.use(router)
app.listen(port)
console.log(`Relayer ${version} started on port ${port}`)
